GO

/* Remove foreign key constraints if they exist, so as to 
not conflict with removal attempts on primary keys */

IF OBJECT_ID('FK_EXAMINATION_IMAGE_EXAM','F') IS NOT NULL
ALTER TABLE dbo.EXAMINATION_IMAGE DROP CONSTRAINT FK_EXAMINATION_IMAGE_EXAM
GO

IF OBJECT_ID('FK_EXAMINATION_IMAGE_IMAGE','F') IS NOT NULL
ALTER TABLE dbo.EXAMINATION_IMAGE DROP CONSTRAINT FK_EXAMINATION_IMAGE_IMAGE
GO

IF OBJECT_ID('FK_CANCER_IMAGE_IMAGE','F') IS NOT NULL
ALTER TABLE dbo.CANCER_IMAGE DROP CONSTRAINT FK_CANCER_IMAGE_IMAGE
GO


IF OBJECT_ID('FK_CANCER_IMAGE_CANCER','F') IS NOT NULL
ALTER TABLE dbo.CANCER_IMAGE DROP CONSTRAINT FK_CANCER_IMAGE_CANCER
GO


IF OBJECT_ID('FK_PREVENT_WAY_IMAGE_PREVENT_WAY','F') IS NOT NULL
ALTER TABLE dbo.PREVENT_WAY_IMAGE DROP CONSTRAINT FK_PREVENT_WAY_IMAGE_PREVENT_WAY
GO


IF OBJECT_ID('FK_PREVENT_WAY_IMAGE_IMAGE','F') IS NOT NULL
ALTER TABLE dbo.PREVENT_WAY_IMAGE DROP CONSTRAINT FK_PREVENT_WAY_IMAGE_IMAGE
GO


IF OBJECT_ID('FK_EXAMINATION_CANCER_EXAM','F') IS NOT NULL
ALTER TABLE dbo.EXAMINATION_CANCER DROP CONSTRAINT FK_EXAMINATION_CANCER_EXAM
GO

IF OBJECT_ID('FK_EXAMINATION_CANCER_CANCER','F') IS NOT NULL
ALTER TABLE dbo.EXAMINATION_CANCER DROP CONSTRAINT FK_EXAMINATION_CANCER_CANCER
GO

IF OBJECT_ID('FK_CANCER_PREVENTION_CANCER','F') IS NOT NULL
ALTER TABLE dbo.CANCER_PREVENTION DROP CONSTRAINT FK_CANCER_PREVENTION_CANCER
GO

IF OBJECT_ID('FK_CANCER_PREVENTION_PREVENTION','F') IS NOT NULL
ALTER TABLE dbo.CANCER_PREVENTION DROP CONSTRAINT FK_CANCER_PREVENTION_PREVENTION
GO

IF OBJECT_ID('FK_CANCER_PREVENTION_PREVENTION','F') IS NOT NULL
ALTER TABLE dbo.CANCER_PREVENTION DROP CONSTRAINT FK_CANCER_PREVENTION_PREVENTION
GO

/* Primary Key Constraints */
IF OBJECT_ID('PK_EXAMINATION','PK') IS NOT NULL
ALTER TABLE dbo.EXAMINATION DROP CONSTRAINT PK_EXAMINATION
GO
ALTER TABLE dbo.EXAMINATION
ADD CONSTRAINT PK_EXAMINATION PRIMARY KEY CLUSTERED (ID_Examination ASC)
GO

IF OBJECT_ID('PK_EXAMINATION_IMAGE','PK') IS NOT NULL
ALTER TABLE dbo.EXAMINATION_IMAGE DROP CONSTRAINT PK_EXAMINATION_IMAGE
GO
ALTER TABLE dbo.EXAMINATION_IMAGE
ADD CONSTRAINT PK_EXAMINATION_IMAGE PRIMARY KEY CLUSTERED (ID_Examination, ID_examination_image ASC)
GO

IF OBJECT_ID('PK_CANCER','PK') IS NOT NULL
ALTER TABLE dbo.CANCER DROP CONSTRAINT PK_CANCER
GO
ALTER TABLE dbo.CANCER
ADD CONSTRAINT PK_CANCER PRIMARY KEY CLUSTERED (ID_cancer ASC)
GO

IF OBJECT_ID('PK_CANCER_IMAGE','PK') IS NOT NULL
ALTER TABLE dbo.CANCER_IMAGE DROP CONSTRAINT PK_CANCER_IMAGE
GO
ALTER TABLE dbo.CANCER_IMAGE
ADD CONSTRAINT PK_CANCER_IMAGE PRIMARY KEY CLUSTERED (ID_cancer, ID_cancer_image ASC)
GO

IF OBJECT_ID('PK_PREVENT_WAY','PK') IS NOT NULL
ALTER TABLE dbo.PREVENT_WAY DROP CONSTRAINT PK_PREVENT_WAY
GO
ALTER TABLE dbo.PREVENT_WAY
ADD CONSTRAINT PK_PREVENT_WAY PRIMARY KEY CLUSTERED (ID_prevent_way ASC)
GO

IF OBJECT_ID('PK_PREVENT_WAY_IMAGE','PK') IS NOT NULL
ALTER TABLE dbo.PREVENT_WAY_IMAGE DROP CONSTRAINT PK_PREVENT_WAY_IMAGE
GO
ALTER TABLE dbo.PREVENT_WAY_IMAGE
ADD CONSTRAINT PK_PREVENT_WAY_IMAGE PRIMARY KEY CLUSTERED (ID_prevent_way, ID_prevent_way_image ASC)
GO

IF OBJECT_ID('PK_EXAMINATION_CANCER','PK') IS NOT NULL
ALTER TABLE dbo.EXAMINATION_CANCER DROP CONSTRAINT PK_EXAMINATION_CANCER
GO
ALTER TABLE dbo.EXAMINATION_CANCER
ADD CONSTRAINT PK_EXAMINATION_CANCER PRIMARY KEY CLUSTERED (ID_Examination, ID_cancer ASC)
GO

IF OBJECT_ID('PK_CANCER_PREVENTION','PK') IS NOT NULL
ALTER TABLE dbo.CANCER_PREVENTION DROP CONSTRAINT PK_CANCER_PREVENTION
GO
ALTER TABLE dbo.CANCER_PREVENTION
ADD CONSTRAINT PK_CANCER_PREVENTION PRIMARY KEY CLUSTERED (ID_cancer, ID_prevent_way ASC)
GO

IF OBJECT_ID('PK_IMAGE','PK') IS NOT NULL
ALTER TABLE dbo.IMAGE DROP CONSTRAINT PK_IMAGE
GO
ALTER TABLE dbo.IMAGE
ADD CONSTRAINT PK_IMAGE PRIMARY KEY CLUSTERED (ID_image ASC)
GO


/* Unique Constraints */

IF OBJECT_ID('UQ_EXAMINATION_NAME','UQ') IS NOT NULL
ALTER TABLE dbo.EXAMIANTION DROP CONSTRAINT UQ_EXAMINATION_NAME
GO
ALTER TABLE dbo.EXAMINATION
ADD CONSTRAINT UQ_EXAMINATION_NAME UNIQUE (examination_name)
GO

IF OBJECT_ID('UQ_CANCER_NAME','UQ') IS NOT NULL
ALTER TABLE dbo.CANCER DROP CONSTRAINT UQ_CANCER_NAME
GO
ALTER TABLE dbo.CANCER
ADD CONSTRAINT UQ_CANCER_NAME UNIQUE (cancer_name)
GO

IF OBJECT_ID('UQ_PREVENT_WAY_NAME','UQ') IS NOT NULL
ALTER TABLE dbo.PREVENT_WAY DROP CONSTRAINT UQ_PREVENT_WAY_NAME
GO
ALTER TABLE dbo.PREVENT_WAY
ADD CONSTRAINT UQ_PREVENT_WAY_NAME UNIQUE (prevent_way_name)
GO




/* Foreign Key Constraints */


ALTER TABLE dbo.EXAMINATION_IMAGE
ADD CONSTRAINT FK_EXAMINATION_IMAGE_EXAM FOREIGN KEY (ID_Examination)
REFERENCES dbo.EXAMINATION(ID_Examination)
ON DELETE NO ACTION ON UPDATE CASCADE
GO

ALTER TABLE dbo.EXAMINATION_IMAGE
ADD CONSTRAINT FK_EXAMINATION_IMAGE_IMAGE FOREIGN KEY (ID_examination_image)
REFERENCES dbo.IMAGE(ID_Image)
ON DELETE NO ACTION ON UPDATE CASCADE
GO

ALTER TABLE dbo.CANCER_IMAGE
ADD CONSTRAINT FK_CANCER_IMAGE_CANCER FOREIGN KEY (ID_cancer)
REFERENCES dbo.CANCER(ID_cancer)
ON DELETE NO ACTION ON UPDATE CASCADE
GO

ALTER TABLE dbo.CANCER_IMAGE
ADD CONSTRAINT FK_CANCER_IMAGE_IMAGE FOREIGN KEY (ID_cancer_image)
REFERENCES dbo.IMAGE(ID_Image)
ON DELETE NO ACTION ON UPDATE CASCADE
GO

ALTER TABLE dbo.PREVENT_WAY_IMAGE
ADD CONSTRAINT FK_PREVENT_WAY_IMAGE_PREVENT_WAY FOREIGN KEY (ID_prevent_way)
REFERENCES dbo.PREVENT_WAY(ID_prevent_way)
ON DELETE NO ACTION ON UPDATE CASCADE
GO

ALTER TABLE dbo.PREVENT_WAY_IMAGE
ADD CONSTRAINT FK_PREVENT_WAY_IMAGE_IMAGE FOREIGN KEY (ID_prevent_way_image)
REFERENCES dbo.IMAGE(ID_Image)
ON DELETE NO ACTION ON UPDATE CASCADE
GO


ALTER TABLE dbo.EXAMINATION_CANCER
ADD CONSTRAINT FK_EXAMINATION_CANCER_EXAM FOREIGN KEY (ID_examination)
REFERENCES dbo.EXAMINATION(ID_Examination)
ON DELETE NO ACTION ON UPDATE CASCADE
GO

ALTER TABLE dbo.EXAMINATION_CANCER
ADD CONSTRAINT FK_EXAMINATION_CANCER_CANCER FOREIGN KEY (ID_cancer)
REFERENCES dbo.CANCER(ID_cancer)
ON DELETE NO ACTION ON UPDATE CASCADE
GO


ALTER TABLE dbo.CANCER_PREVENTION
ADD CONSTRAINT FK_CANCER_PREVENTION_CANCER FOREIGN KEY (ID_cancer)
REFERENCES dbo.CANCER(ID_cancer)
ON DELETE NO ACTION ON UPDATE CASCADE
GO

ALTER TABLE dbo.CANCER_PREVENTION
ADD CONSTRAINT FK_CANCER_PREVENTION_PREVENTION FOREIGN KEY (ID_prevent_way)
REFERENCES dbo.PREVENT_WAY(ID_prevent_way)
ON DELETE NO ACTION ON UPDATE CASCADE
GO


/* Check Constraints */

IF OBJECT_ID('CH_EXAMINATION_FREQUENCY','C') IS NOT NULL
ALTER TABLE dbo.EXAMINATION DROP CONSTRAINT CH_EXAMINATION_FREQUENCY
GO
ALTER TABLE dbo.EXAMINATION
ADD CONSTRAINT CH_EXAMINATION_FREQUENCY CHECK (examination_frequency > 0)
GO

