/* Primary Key Constraints */
IF OBJECT_ID('PK_EXAMINATION','PK') IS NOT NULL
ALTER TABLE dbo.EXAMINATION DROP CONSTRAINT PK_EXAMINATION
GO
ALTER TABLE dbo.EXAMINATION
ADD CONSTRAINT PK_EXAMINATION PRIMARY KEY CLUSTERED (ID_Examination ASC)
GO

IF OBJECT_ID('PK_EXAMINATION_IMAGE','PK') IS NOT NULL
ALTER TABLE dbo.EXAMINATION_IMAGE DROP CONSTRAINT PK_EXAMINATION_IMAGE
GO
ALTER TABLE dbo.EXAMINATION_IMAGE
ADD CONSTRAINT PK_EXAMINATION_IMAGE PRIMARY KEY CLUSTERED (ID_Examination, examination_image ASC)
GO

IF OBJECT_ID('PK_CANCER','PK') IS NOT NULL
ALTER TABLE dbo.CANCER DROP CONSTRAINT PK_CANCER
GO
ALTER TABLE dbo.CANCER
ADD CONSTRAINT PK_CANCER PRIMARY KEY CLUSTERED (ID_cancer ASC)
GO

IF OBJECT_ID('PK_CANCER_IMAGE','PK') IS NOT NULL
ALTER TABLE dbo.CANCER_IMAGE DROP CONSTRAINT PK_CANCER_IMAGE
GO
ALTER TABLE dbo.CANCER_IMAGE
ADD CONSTRAINT PK_CANCER_IMAGE PRIMARY KEY CLUSTERED (ID_cancer, cancer_image ASC)
GO

IF OBJECT_ID('PK_PREVENT_WAY','PK') IS NOT NULL
ALTER TABLE dbo.PREVENT_WAY DROP CONSTRAINT PK_PREVENT_WAY
GO
ALTER TABLE dbo.PREVENT_WAY
ADD CONSTRAINT PK_PREVENT_WAY PRIMARY KEY CLUSTERED (ID_prevent_way ASC)
GO

IF OBJECT_ID('PK_PREVENT_WAY_IMAGE','PK') IS NOT NULL
ALTER TABLE dbo.PREVENT_WAY_IMAGE DROP CONSTRAINT PK_PREVENT_WAY_IMAGE
GO
ALTER TABLE dbo.PREVENT_WAY_IMAGE
ADD CONSTRAINT PK_PREVENT_WAY_IMAGE PRIMARY KEY CLUSTERED (ID_prevent_way, prevent_way_image ASC)
GO

IF OBJECT_ID('PK_EXAMINATION_CANCER','PK') IS NOT NULL
ALTER TABLE dbo.EXAMINATION_CANCER DROP CONSTRAINT PK_EXAMINATION_CANCER
GO
ALTER TABLE dbo.EXAMINATION_CANCER
ADD CONSTRAINT PK_EXAMINATION_CANCER PRIMARY KEY CLUSTERED (ID_Examination, ID_cancer ASC)
GO

IF OBJECT_ID('PK_CANCER_PREVENTION','PK') IS NOT NULL
ALTER TABLE dbo.CANCER_PREVENTION DROP CONSTRAINT PK_CANCER_PREVENTION
GO
ALTER TABLE dbo.CANCER_PREVENTION
ADD CONSTRAINT PK_CANCER_PREVENTION PRIMARY KEY CLUSTERED (ID_cancer, ID_prevent_way ASC)
GO